apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service-deployment
  labels:
    app: data-pcap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-pcap  
  template:
    metadata:
      labels:
        app: data-pcap  
    spec:
      containers:
      - name: data-pcap 
        image: hotshot07/pcap-service:latest
        imagePullPolicy: Always
        command: ["/bin/sh","-c"]
        args: ["python3 data_server.py"]
        ports:
        - containerPort: 5000

---
kind: Service
apiVersion: v1
metadata:
  name: data-service 
spec:
  type: ClusterIP
  selector:
    app: data-pcap
  ports:
  # Default port used by the image
  - port: 5000
