apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-vue
  labels:
    app: frontend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend  
  template:
    metadata:
      labels:
        app: frontend  
    spec:
      containers:
      - name: frontend-vue 
        image: hotshot07/frontend-vue:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: frontend-vue-service
spec:
  type: LoadBalancer
  selector:
    app: frontend 
  ports:
  # Default port used by the image
  - port: 80