apiVersion: v1
kind: Pod
metadata:
  name: tcpdump-pod
  namespace: kube-system
spec:
  containers:
  - name: tcpboi
    image:  hotshot07/debug-container
    command: ['sh', '-c', 'sleep 999']
    securityContext:
       privileged: true